// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.8
// source: txpool/sealing.proto

package txpool

import (
	types "github.com/ledgerwatch/erigon-lib/gointerfaces/types"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SealRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Params          *BlockParameters `protobuf:"bytes,1,opt,name=params,proto3" json:"params,omitempty"`
	FillWithMempool bool             `protobuf:"varint,2,opt,name=fillWithMempool,proto3" json:"fillWithMempool,omitempty"`
	Trace           bool             `protobuf:"varint,3,opt,name=trace,proto3" json:"trace,omitempty"`
	RlpTxs          [][]byte         `protobuf:"bytes,16,rep,name=rlpTxs,proto3" json:"rlpTxs,omitempty"`
}

func (x *SealRequest) Reset() {
	*x = SealRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_txpool_sealing_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SealRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SealRequest) ProtoMessage() {}

func (x *SealRequest) ProtoReflect() protoreflect.Message {
	mi := &file_txpool_sealing_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SealRequest.ProtoReflect.Descriptor instead.
func (*SealRequest) Descriptor() ([]byte, []int) {
	return file_txpool_sealing_proto_rawDescGZIP(), []int{0}
}

func (x *SealRequest) GetParams() *BlockParameters {
	if x != nil {
		return x.Params
	}
	return nil
}

func (x *SealRequest) GetFillWithMempool() bool {
	if x != nil {
		return x.FillWithMempool
	}
	return false
}

func (x *SealRequest) GetTrace() bool {
	if x != nil {
		return x.Trace
	}
	return false
}

func (x *SealRequest) GetRlpTxs() [][]byte {
	if x != nil {
		return x.RlpTxs
	}
	return nil
}

type BlockParameters struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ParentHash *types.H256 `protobuf:"bytes,1,opt,name=parentHash,proto3" json:"parentHash,omitempty"`
	Coinbase   *types.H160 `protobuf:"bytes,2,opt,name=coinbase,proto3" json:"coinbase,omitempty"`
	Timestamp  uint64      `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	GasLimit   uint64      `protobuf:"varint,4,opt,name=gasLimit,proto3" json:"gasLimit,omitempty"`
	Random     *types.H256 `protobuf:"bytes,5,opt,name=random,proto3" json:"random,omitempty"`
	ExtraData  []byte      `protobuf:"bytes,6,opt,name=extraData,proto3" json:"extraData,omitempty"`
}

func (x *BlockParameters) Reset() {
	*x = BlockParameters{}
	if protoimpl.UnsafeEnabled {
		mi := &file_txpool_sealing_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BlockParameters) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockParameters) ProtoMessage() {}

func (x *BlockParameters) ProtoReflect() protoreflect.Message {
	mi := &file_txpool_sealing_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockParameters.ProtoReflect.Descriptor instead.
func (*BlockParameters) Descriptor() ([]byte, []int) {
	return file_txpool_sealing_proto_rawDescGZIP(), []int{1}
}

func (x *BlockParameters) GetParentHash() *types.H256 {
	if x != nil {
		return x.ParentHash
	}
	return nil
}

func (x *BlockParameters) GetCoinbase() *types.H160 {
	if x != nil {
		return x.Coinbase
	}
	return nil
}

func (x *BlockParameters) GetTimestamp() uint64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *BlockParameters) GetGasLimit() uint64 {
	if x != nil {
		return x.GasLimit
	}
	return 0
}

func (x *BlockParameters) GetRandom() *types.H256 {
	if x != nil {
		return x.Random
	}
	return nil
}

func (x *BlockParameters) GetExtraData() []byte {
	if x != nil {
		return x.ExtraData
	}
	return nil
}

type ExcludedTransaction struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Hash   *types.H256 `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	Reason string      `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
}

func (x *ExcludedTransaction) Reset() {
	*x = ExcludedTransaction{}
	if protoimpl.UnsafeEnabled {
		mi := &file_txpool_sealing_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExcludedTransaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExcludedTransaction) ProtoMessage() {}

func (x *ExcludedTransaction) ProtoReflect() protoreflect.Message {
	mi := &file_txpool_sealing_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExcludedTransaction.ProtoReflect.Descriptor instead.
func (*ExcludedTransaction) Descriptor() ([]byte, []int) {
	return file_txpool_sealing_proto_rawDescGZIP(), []int{2}
}

func (x *ExcludedTransaction) GetHash() *types.H256 {
	if x != nil {
		return x.Hash
	}
	return nil
}

func (x *ExcludedTransaction) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type SealResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Profit               []byte                  `protobuf:"bytes,1,opt,name=profit,proto3" json:"profit,omitempty"`
	Payload              *types.ExecutionPayload `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	ExcludedTransactions []*ExcludedTransaction  `protobuf:"bytes,16,rep,name=excludedTransactions,proto3" json:"excludedTransactions,omitempty"`
	Receipts             [][]byte                `protobuf:"bytes,17,rep,name=receipts,proto3" json:"receipts,omitempty"`
	Traces               []string                `protobuf:"bytes,18,rep,name=traces,proto3" json:"traces,omitempty"`
}

func (x *SealResponse) Reset() {
	*x = SealResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_txpool_sealing_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SealResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SealResponse) ProtoMessage() {}

func (x *SealResponse) ProtoReflect() protoreflect.Message {
	mi := &file_txpool_sealing_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SealResponse.ProtoReflect.Descriptor instead.
func (*SealResponse) Descriptor() ([]byte, []int) {
	return file_txpool_sealing_proto_rawDescGZIP(), []int{3}
}

func (x *SealResponse) GetProfit() []byte {
	if x != nil {
		return x.Profit
	}
	return nil
}

func (x *SealResponse) GetPayload() *types.ExecutionPayload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *SealResponse) GetExcludedTransactions() []*ExcludedTransaction {
	if x != nil {
		return x.ExcludedTransactions
	}
	return nil
}

func (x *SealResponse) GetReceipts() [][]byte {
	if x != nil {
		return x.Receipts
	}
	return nil
}

func (x *SealResponse) GetTraces() []string {
	if x != nil {
		return x.Traces
	}
	return nil
}

var File_txpool_sealing_proto protoreflect.FileDescriptor

var file_txpool_sealing_proto_rawDesc = []byte{
	0x0a, 0x14, 0x74, 0x78, 0x70, 0x6f, 0x6f, 0x6c, 0x2f, 0x73, 0x65, 0x61, 0x6c, 0x69, 0x6e, 0x67,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x74, 0x78, 0x70, 0x6f, 0x6f, 0x6c, 0x1a, 0x11,
	0x74, 0x79, 0x70, 0x65, 0x73, 0x2f, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0x96, 0x01, 0x0a, 0x0b, 0x53, 0x65, 0x61, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x2f, 0x0a, 0x06, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x17, 0x2e, 0x74, 0x78, 0x70, 0x6f, 0x6f, 0x6c, 0x2e, 0x42, 0x6c, 0x6f, 0x63, 0x6b,
	0x50, 0x61, 0x72, 0x61, 0x6d, 0x65, 0x74, 0x65, 0x72, 0x73, 0x52, 0x06, 0x70, 0x61, 0x72, 0x61,
	0x6d, 0x73, 0x12, 0x28, 0x0a, 0x0f, 0x66, 0x69, 0x6c, 0x6c, 0x57, 0x69, 0x74, 0x68, 0x4d, 0x65,
	0x6d, 0x70, 0x6f, 0x6f, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0f, 0x66, 0x69, 0x6c,
	0x6c, 0x57, 0x69, 0x74, 0x68, 0x4d, 0x65, 0x6d, 0x70, 0x6f, 0x6f, 0x6c, 0x12, 0x14, 0x0a, 0x05,
	0x74, 0x72, 0x61, 0x63, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x74, 0x72, 0x61,
	0x63, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x6c, 0x70, 0x54, 0x78, 0x73, 0x18, 0x10, 0x20, 0x03,
	0x28, 0x0c, 0x52, 0x06, 0x72, 0x6c, 0x70, 0x54, 0x78, 0x73, 0x22, 0xe4, 0x01, 0x0a, 0x0f, 0x42,
	0x6c, 0x6f, 0x63, 0x6b, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x65, 0x74, 0x65, 0x72, 0x73, 0x12, 0x2b,
	0x0a, 0x0a, 0x70, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x48, 0x61, 0x73, 0x68, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x48, 0x32, 0x35, 0x36, 0x52,
	0x0a, 0x70, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x48, 0x61, 0x73, 0x68, 0x12, 0x27, 0x0a, 0x08, 0x63,
	0x6f, 0x69, 0x6e, 0x62, 0x61, 0x73, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e,
	0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x48, 0x31, 0x36, 0x30, 0x52, 0x08, 0x63, 0x6f, 0x69, 0x6e,
	0x62, 0x61, 0x73, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d,
	0x70, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61,
	0x6d, 0x70, 0x12, 0x1a, 0x0a, 0x08, 0x67, 0x61, 0x73, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x04, 0x52, 0x08, 0x67, 0x61, 0x73, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x12, 0x23,
	0x0a, 0x06, 0x72, 0x61, 0x6e, 0x64, 0x6f, 0x6d, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b,
	0x2e, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x48, 0x32, 0x35, 0x36, 0x52, 0x06, 0x72, 0x61, 0x6e,
	0x64, 0x6f, 0x6d, 0x12, 0x1c, 0x0a, 0x09, 0x65, 0x78, 0x74, 0x72, 0x61, 0x44, 0x61, 0x74, 0x61,
	0x18, 0x06, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x09, 0x65, 0x78, 0x74, 0x72, 0x61, 0x44, 0x61, 0x74,
	0x61, 0x22, 0x4e, 0x0a, 0x13, 0x45, 0x78, 0x63, 0x6c, 0x75, 0x64, 0x65, 0x64, 0x54, 0x72, 0x61,
	0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1f, 0x0a, 0x04, 0x68, 0x61, 0x73, 0x68,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x48,
	0x32, 0x35, 0x36, 0x52, 0x04, 0x68, 0x61, 0x73, 0x68, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x61,
	0x73, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x61, 0x73, 0x6f,
	0x6e, 0x22, 0xde, 0x01, 0x0a, 0x0c, 0x53, 0x65, 0x61, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x72, 0x6f, 0x66, 0x69, 0x74, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x06, 0x70, 0x72, 0x6f, 0x66, 0x69, 0x74, 0x12, 0x31, 0x0a, 0x07, 0x70, 0x61,
	0x79, 0x6c, 0x6f, 0x61, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x74, 0x79,
	0x70, 0x65, 0x73, 0x2e, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x50, 0x61, 0x79,
	0x6c, 0x6f, 0x61, 0x64, 0x52, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x12, 0x4f, 0x0a,
	0x14, 0x65, 0x78, 0x63, 0x6c, 0x75, 0x64, 0x65, 0x64, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x10, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x74, 0x78,
	0x70, 0x6f, 0x6f, 0x6c, 0x2e, 0x45, 0x78, 0x63, 0x6c, 0x75, 0x64, 0x65, 0x64, 0x54, 0x72, 0x61,
	0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x14, 0x65, 0x78, 0x63, 0x6c, 0x75, 0x64,
	0x65, 0x64, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x1a,
	0x0a, 0x08, 0x72, 0x65, 0x63, 0x65, 0x69, 0x70, 0x74, 0x73, 0x18, 0x11, 0x20, 0x03, 0x28, 0x0c,
	0x52, 0x08, 0x72, 0x65, 0x63, 0x65, 0x69, 0x70, 0x74, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x74, 0x72,
	0x61, 0x63, 0x65, 0x73, 0x18, 0x12, 0x20, 0x03, 0x28, 0x09, 0x52, 0x06, 0x74, 0x72, 0x61, 0x63,
	0x65, 0x73, 0x32, 0x41, 0x0a, 0x07, 0x53, 0x65, 0x61, 0x6c, 0x69, 0x6e, 0x67, 0x12, 0x36, 0x0a,
	0x09, 0x53, 0x65, 0x61, 0x6c, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x12, 0x13, 0x2e, 0x74, 0x78, 0x70,
	0x6f, 0x6f, 0x6c, 0x2e, 0x53, 0x65, 0x61, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x14, 0x2e, 0x74, 0x78, 0x70, 0x6f, 0x6f, 0x6c, 0x2e, 0x53, 0x65, 0x61, 0x6c, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x11, 0x5a, 0x0f, 0x2e, 0x2f, 0x74, 0x78, 0x70, 0x6f, 0x6f,
	0x6c, 0x3b, 0x74, 0x78, 0x70, 0x6f, 0x6f, 0x6c, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_txpool_sealing_proto_rawDescOnce sync.Once
	file_txpool_sealing_proto_rawDescData = file_txpool_sealing_proto_rawDesc
)

func file_txpool_sealing_proto_rawDescGZIP() []byte {
	file_txpool_sealing_proto_rawDescOnce.Do(func() {
		file_txpool_sealing_proto_rawDescData = protoimpl.X.CompressGZIP(file_txpool_sealing_proto_rawDescData)
	})
	return file_txpool_sealing_proto_rawDescData
}

var file_txpool_sealing_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_txpool_sealing_proto_goTypes = []interface{}{
	(*SealRequest)(nil),            // 0: txpool.SealRequest
	(*BlockParameters)(nil),        // 1: txpool.BlockParameters
	(*ExcludedTransaction)(nil),    // 2: txpool.ExcludedTransaction
	(*SealResponse)(nil),           // 3: txpool.SealResponse
	(*types.H256)(nil),             // 4: types.H256
	(*types.H160)(nil),             // 5: types.H160
	(*types.ExecutionPayload)(nil), // 6: types.ExecutionPayload
}
var file_txpool_sealing_proto_depIdxs = []int32{
	1, // 0: txpool.SealRequest.params:type_name -> txpool.BlockParameters
	4, // 1: txpool.BlockParameters.parentHash:type_name -> types.H256
	5, // 2: txpool.BlockParameters.coinbase:type_name -> types.H160
	4, // 3: txpool.BlockParameters.random:type_name -> types.H256
	4, // 4: txpool.ExcludedTransaction.hash:type_name -> types.H256
	6, // 5: txpool.SealResponse.payload:type_name -> types.ExecutionPayload
	2, // 6: txpool.SealResponse.excludedTransactions:type_name -> txpool.ExcludedTransaction
	0, // 7: txpool.Sealing.SealBlock:input_type -> txpool.SealRequest
	3, // 8: txpool.Sealing.SealBlock:output_type -> txpool.SealResponse
	8, // [8:9] is the sub-list for method output_type
	7, // [7:8] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_txpool_sealing_proto_init() }
func file_txpool_sealing_proto_init() {
	if File_txpool_sealing_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_txpool_sealing_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SealRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_txpool_sealing_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BlockParameters); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_txpool_sealing_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExcludedTransaction); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_txpool_sealing_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SealResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_txpool_sealing_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_txpool_sealing_proto_goTypes,
		DependencyIndexes: file_txpool_sealing_proto_depIdxs,
		MessageInfos:      file_txpool_sealing_proto_msgTypes,
	}.Build()
	File_txpool_sealing_proto = out.File
	file_txpool_sealing_proto_rawDesc = nil
	file_txpool_sealing_proto_goTypes = nil
	file_txpool_sealing_proto_depIdxs = nil
}
